src/Entity/Descriptions.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DescriptionsRepository")
 */
class Descriptions
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $opption;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $contenu;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produits", inversedBy="descriptions")
     */
    private $produits;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Jours;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getOpption(): ?string
    {
        return $this->opption;
    }

    public function setOpption(string $opption): self
    {
        $this->opption = $opption;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getProduits(): ?Produits
    {
        return $this->produits;
    }

    public function setProduits(?Produits $produits): self
    {
        $this->produits = $produits;

        return $this;
    }

    public function getJours(): ?string
    {
        return $this->Jours;
    }

    public function setJours(string $Jours): self
    {
        $this->Jours = $Jours;

        return $this;
    }
    public function __toString()
    {
        return (string) $this->titre;
    }
}

src/Form/DescriptionsType.php
<?php

namespace App\Form;

use App\Entity\Descriptions;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DescriptionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {

        $builder
            ->add('titre')
            ->add('opption')
            ->add('contenu',CKEditorType::class,array(
                'config'=>array(
                    'height'=> 260,
                    'width'=> 1000,
                     'uiColor'=>'#3c8dbc',

                ),

             ))
            ->add('Jours')
            ->add('produits')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Descriptions::class,
        ]);
    }
}

src/Controller/DescriptionsController.php
<?php

namespace App\Controller;

use App\Entity\Descriptions;
use App\Form\DescriptionsType;
use App\Repository\DescriptionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/descriptions")
 */
class DescriptionsController extends AbstractController
{
    /**
     * @Route("/", name="descriptions_index", methods={"GET"})
     */
    public function index(DescriptionsRepository $descriptionsRepository): Response
    {
        return $this->render('descriptions/index.html.twig', [
            'descriptions' => $descriptionsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="descriptions_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $description = new Descriptions();
        $form = $this->createForm(DescriptionsType::class, $description);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($description);
            $entityManager->flush();

            return $this->redirectToRoute('descriptions_index');
        }

        return $this->render('descriptions/new.html.twig', [
            'description' => $description,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="descriptions_show", methods={"GET"})
     */
    public function show(Descriptions $description): Response
    {
        return $this->render('descriptions/show.html.twig', [
            'description' => $description,
        ]);
    }
    /**
     * @Route("/{id}", name="descriptions_produit", methods={"GET"})
     */
    public function showDesProd(DescriptionsRepository $descriptionsRepository,Descriptions $description): Response
    {
       // return $this->render('descriptions/show.html.twig', [
       //     'description' => $description,
      //  ]);

            return $this->render('descriptions/produit.html.twig', [
                'descriptions' => $descriptionsRepository->findByProduits($description->getProduits())
            ]);

    }

    /**
     * @Route("/{id}/edit", name="descriptions_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Descriptions $description): Response
    {
        $form = $this->createForm(DescriptionsType::class, $description);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('descriptions_index');
        }

        return $this->render('descriptions/edit.html.twig', [
            'description' => $description,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="descriptions_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Descriptions $description): Response
    {
        if ($this->isCsrfTokenValid('delete'.$description->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($description);
            $entityManager->flush();
        }

        return $this->redirectToRoute('descriptions_index');
    }
}

templates/descriptions/_delete_form.html.twig
<form method="post" action="{{ path('descriptions_delete', {'id': description.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ description.id) }}">
    <button class="btn">Delete</button>
</form>

templates/descriptions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/descriptions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Descriptions{% endblock %}

{% block body %}
    <h1>Edit Descriptions</h1>

    {{ include('descriptions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('descriptions_index') }}">back to list</a>

    {{ include('descriptions/_delete_form.html.twig') }}
{% endblock %}

templates/descriptions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Descriptions index{% endblock %}

{% block body %}
    <h1>Descriptions index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Opption</th>
                <th>Contenu</th>
                <th>Jours</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for description in descriptions %}
            <tr>
                <td>{{ description.id }}</td>
                <td>{{ description.titre }}</td>
                <td>{{ description.opption }}</td>
                <td>{{ description.contenu }}</td>
                <td>{{ description.jours }}</td>
                <td>
                    <a href="{{ path('descriptions_show', {'id': description.id}) }}">show</a>
                    <a href="{{ path('descriptions_edit', {'id': description.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('descriptions_new') }}">Create new</a>
{% endblock %}

templates/descriptions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Descriptions{% endblock %}

{% block body %}
    <h1>Create new Descriptions</h1>

    {{ include('descriptions/_form.html.twig') }}

    <a href="{{ path('descriptions_index') }}">back to list</a>
{% endblock %}

templates/descriptions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Descriptions{% endblock %}

{% block body %}
    <h1>Descriptions</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ description.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ description.titre }}</td>
            </tr>
            <tr>
                <th>Opption</th>
                <td>{{ description.opption }}</td>
            </tr>
            <tr>
                <th>Contenu</th>
                <td>{{ description.contenu }}</td>
            </tr>
            <tr>
                <th>Jours</th>
                <td>{{ description.jours }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('descriptions_index') }}">back to list</a>

    <a href="{{ path('descriptions_edit', {'id': description.id}) }}">edit</a>

    {{ include('descriptions/_delete_form.html.twig') }}
{% endblock %}